apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data-db
spec:
  storageClassName: nfs-rwx-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi