# Define ApisixTls Objects
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: api-tls
  namespace: stock-trad
spec:
  hosts:
  - api.sisox.site
  - auth.sisox.site
  secret:
    name: sisox-tls-secret
    namespace: stock-trad
---    
# Define the route to access the backend
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: api-route
  namespace: stock-trad
spec:
  http:
  - name: api.sisox.site
    match:
      hosts:
      - api.sisox.site
      paths:
      - /*
    backends:
    - serviceName: httpbin
      servicePort: 80
  - name: auth.sisox.site
    match:
      hosts:
      - auth.sisox.site
      paths:
      - /*
    backends:
    - serviceName: keycloak-headless
      servicePort: 80