apiVersion: v1
kind: Service
metadata:
  name: ext-api-service
  namespace: ingress-apisix
spec:
  type: ExternalName
  externalName: httpbin.api-service.svc.cluster.local
---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: ext-api-upstream
  namespace: ingress-apisix
spec:
  externalNodes:
  - type: Service
    name: ext-api-service
---
# Define ApisixTls Objects
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: api-tls
  namespace: ingress-apisix
spec:
  hosts:
  - api.sisox.site
  secret:
    name: sisox-tls-secret
    namespace: ingress-apisix
---
# Define the route to access the backend
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: api-route
  namespace: ingress-apisix
spec:
  http:
  - name: api.sisox.site
    match:
      paths:
      - /*
    upstreams:
    - name: ext-api-upstream