# Define ApisixTls Objects
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: api-tls
  namespace: stock-trad
spec:
  hosts:
  - api.sisox.site
  - auth.sisox.site
  secret:
    name: sisox-tls-secret
    namespace: stock-trad
---
# Define the route to access the backend
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: api-route
  namespace: stock-trad
spec:
  http:
  - name: api.sisox.site
    match:
      hosts:
      - api.sisox.site
      paths:
      - /bin*
    plugins:
    - name: proxy-rewrite
      enable: true
      config: 
        regex_uri:
        - "^/bin/*"
        - /$1
    - name: openid-connect
      enable: true
      config:
        client_id: api
        client_secret: Xiz7wTtYTA46G4p7GZR9Bt6QtYft2OxR
        discovery: http://auth.sisox.site/realms/stock/.well-known/openid-configuration
        bearer_only: true
        realm: stock
    backends:
    - serviceName: httpbin
      servicePort: 80
  - name: auth.sisox.site
    match:
      hosts:
      - auth.sisox.site
      paths:
      - /*
    backends:
    - serviceName: keycloak-headless
      servicePort: 80