apiVersion: v1
kind: Service
metadata:
  name: camarero
  namespace: sisox
  labels:
    app: camarero
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: camarero
  ports:
    - protocol: TCP
      port: 80