apiVersion: apps/v1
kind: Deployment
metadata:
  name: camarero
  namespace: sisox
  labels:
    app: camarero
spec:
  replicas: 2
  selector:
    matchLabels:
      app: camarero
  template:
    metadata:
      labels:
        app: camarero
    spec:
      containers:
      - name: yosoy
        image: lukasz/yosoy:2.0.3
        resources:
            requests:
              memory: "4Mi"
              cpu: "50m"
            limits:
              memory: "8Mi"
              cpu: "100m"
        env:
          - name: YOSOY_SHOW_ENVS
            value: "true"
          - name: YOSOY_SHOW_FILES
            value: "/etc/podinfo/labels,/etc/podinfo/annotations"
        ports:
        - containerPort: 80